name: SonarQube Scan and Analysis

on:
  push:
    branches:
      - main

jobs:
  setup-sonarqube:
    name: Set up SonarQube and PostgreSQL
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube
        ports:
          - "9000:9000"
        options: --health-cmd "curl -f http://localhost:9000 || exit 1"
      sonarqube-db:
        image: postgres:alpine
        env:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar
          POSTGRES_DB: sonarqube
        options: --health-cmd "pg_isready -U sonar"

    steps:
      - name: Wait for services to be ready
        run: sleep 30  # Adjust as necessary

  sonarqube-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: setup-sonarqube

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000

      # Add additional steps as needed for your workflow

